################################################################################
# training parameters
################################################################################
train:
  scheduler: 'consine'
  pipeline: "cnn-vit"
  optim: "sgd"
  loss: "xentropy"       # must be either xentropy or iou
  amp: True

  max_epochs: 50
  lr:  0.00001          # sgd learning rate
  consinelr: 0.005
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  Reduce_epoch: 25
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay:  0.0001       # weight decay
  batch_size:  2       # batch size
  report_batch: 100     # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_scans: True       # False doesn't save anything, True saves some

  show_scans: True    # show scans during training
  save_batch: 50      # every x batches, save scans
  workers: 0          # number of threads to get data

################################################################################
# postproc parameters
################################################################################
post:
  CRF:
    use: False
    train: True
    params: False # this should be a dict when in use
  KNN:
    use: True # This parameter default is false
    params:
      knn: 11
      search: 11
      sigma: 1.0
      cutoff: 5.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "poss"
  scans: "poss"
  max_points: 72000 # max of any scan in dataset
  sensor:
    name: "Pandora"
    type: "spherical" # projective
    fov_up: 7
    fov_down: -16
    img_prop:
      width: 1600
      height: 64
    img_means: #range,x,y,z,signal   (40, 1800)
      - 22.26779
      - 0.51144063
      - 1.5727469
      - -0.6350901
      - 13.875261
    img_stds: #range,x,y,z,signal
      - 17.735949
      - 17.422485
      - 22.217215
      - 1.6433295
      - 14.0925865
      
